version: '3.1'
services:
  db:
    image: postgres:11
    container_name: barbershop-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - barbershop-data:/var/lib/postgresql/data
volumes:
  barbershop-data: